# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pramodh
subtitle: Software Engineer
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog on dev activity, outdoors, gaming, books and life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pramodh.dev" # the base hostname & protocol for your site, e.g. http://example.com

# social media
twitter_username: satyapramodh
github_username:  satyapramodh
google_analytics: UA-107278931-1

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-autoprefixer

destination: ./build

# author
author_name: "Pramodh Mazumdar"
author_profile_pic: "https://www.gravatar.com/avatar/de3c5580970c50b7678dcf510478a47f?s=300"

# Navigation 
header_pages:
  - blog.html  
  - portfolio.html

disqus:
    shortname: pramodh-dev

minima:
  social_links:
    twitter: satyapramodh
    github: satyapramodh
    linkedin: satyapramodh

sass:
  sass_dir: _sass
  style: compressed

    # urls:
#   - text: About
#     url: /
#   - text: Blog
#     url: /blog

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# defaults
defaults:
  - 
    scope:  
      path: ""
    values:
      layout: "home"